baseURL = "https://www.greeneyed.org/"
languageCode = "en-us"
title = "GreenEyed's"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "greeneyed"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/greeneyed_dlj"
  instagram = ""
  youtube = ""
  github = "https://github.com/Verdoso/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/dlopezj/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/bellagio.jpg"
  recent_posts_number = 10
  show_reading_time = true
  disqusShortname = "greeneyed"
  custom_css = ["css/greeneyed.css"]

