DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 15
SectionPagesMenu = "main"
baseURL = "https://www.greeneyed.org/"
disqusShortname = "greeneyed"
enableRobotsTXT = true
googleAnalytics = "UA-6249372-1"
languageCode = "en-us"
theme = "ananke"
title = "GreenEyed's"
[params]
background_color_class = "bg-dark-green"
custom_css = ["css/greeneyed.css"]
description = "The last theme you'll ever need. Maybe."
disqusShortname = "greeneyed"
facebook = ""
favicon = ""
featured_image = "/images/bellagio.jpg"
github = "https://github.com/Verdoso/"
gitlab = ""
instagram = ""
linkedin = "https://www.linkedin.com/in/dlopezj/"
mastodon = ""
recent_posts_number = 10
show_reading_time = true
twitter = "https://twitter.com/greeneyed_dlj"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
